### ISSUE TITLE
apiswf is null

### ISSUE THREAD

**Issue by eevah** [rdio/hello-web-playback#4]
Hi,

I am trying to run the code in Chrome, but when I click the play button, I get error:

Uncaught TypeError: Cannot call method 'rdio_play' of null 

I have flash player installed, and I also tried to add swfObject.js to the folder but it didn't help. Can you please help me figure out what is wrong?

Thank you!

**Comment by eevah** [comment]
I figured it out. I didn't start the local server.

**Comment by colemanfoley** [comment]
So how did you start the local server?

**Comment by dasevilla** [comment]
The Web Playback API doesn't work when served from a `file://` URL, you need to run a local web server.

**Comment by colemanfoley** [comment]
Thank you, that worked. I think it might be a good idea for this to be spelled out more clearly in the readme, for novices like me. I spent a long time trying to figure that out.

**Comment by rknLA** [comment]
Good idea!  Added to the README in 4c0abdc8856260cd2062d8ccf3dc015c101c54d9.
